#!/usr/bin/env python3
"""Build ASSET-INDEX.md + assets.json for the RGC Assets folder.

Usage:
  python3 build-asset-index.py <assets-dir> [--base-url URL] [--map map.json]

Link resolution, in order:
  1. --map map.json      {"<relative-path-or-filename>": "<url>", ...}
                         (this is the mode for Google Drive, where every file
                         gets its own ID; build the map from the Drive listing)
  2. --base-url URL      URL + "/" + relative path (for path-preserving hosts:
                         a public bucket, GitHub raw, Vercel/Netlify static)
  3. neither             relative paths (work locally and in most repo viewers)

Google Drive does NOT preserve folder paths in file URLs, so --base-url will
not produce working Drive links. Upload first, then generate the map from the
Drive file listing and re-run with --map.

Re-run after any change to the assets folder; the outputs are generated files.
"""
import os, sys, json, re, urllib.parse

def dims(path):
    ext = os.path.splitext(path)[1].lower()
    if ext == ".svg":
        try:
            head = open(path, "r", errors="ignore").read(2048)
            m = re.search(r'viewBox="[\d.\s-]*?([\d.]+)\s+([\d.]+)"', head)
            if m: return f"{round(float(m.group(1)))}×{round(float(m.group(2)))}"
            w = re.search(r'width="([\d.]+)', head); h = re.search(r'height="([\d.]+)', head)
            if w and h: return f"{round(float(w.group(1)))}×{round(float(h.group(1)))}"
        except Exception: pass
        return "vector"
    try:
        from PIL import Image
        Image.MAX_IMAGE_PIXELS = None
        with Image.open(path) as im: return f"{im.width}×{im.height}"
    except Exception:
        return ""

def human(n):
    for u in ("B", "KB", "MB"):
        if n < 1024 or u == "MB": return f"{n:.1f}{u}" if u != "B" else f"{n}B"
        n /= 1024

def main():
    args = sys.argv[1:]
    if not args: sys.exit(__doc__)
    root = os.path.abspath(args[0])
    base = None; linkmap = {}
    if "--base-url" in args: base = args[args.index("--base-url") + 1].rstrip("/")
    if "--map" in args: linkmap = json.load(open(args[args.index("--map") + 1]))

    entries = []
    for dp, dns, fns in os.walk(root):
        dns[:] = sorted(d for d in dns if d not in ("tools", ".git", ".github"))
        for fn in sorted(fns):
            if fn.startswith(".") or fn in ("ASSET-INDEX.md", "assets.json"): continue
            p = os.path.join(dp, fn)
            rel = os.path.relpath(p, root).replace(os.sep, "/")
            entries.append({
                "path": rel,
                "category": rel.split("/")[0] if "/" in rel else "(root)",
                "bytes": os.path.getsize(p),
                "dimensions": dims(p) if os.path.splitext(fn)[1].lower() in
                    (".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".tif", ".tiff") else "",
                "url": linkmap.get(rel) or linkmap.get(fn) or
                       (f"{base}/{urllib.parse.quote(rel)}" if base else rel),
            })

    with open(os.path.join(root, "assets.json"), "w") as f:
        json.dump({"generated_from": os.path.basename(root), "count": len(entries),
                   "base_url": base, "assets": entries}, f, indent=1)

    cats = {}
    for e in entries: cats.setdefault(e["category"], []).append(e)

    BLURB = {
        "logos": "RGC marks and product marks. `rgc-logo.svg` is the only vector logo; place, never redraw.",
        "icons": "report-icons (156, dark/light pairs, slug names) + mono (78, currentColor) + the seven dimension modules (3D and colour) + 10 shopper archetypes.",
        "image-fills": "The source bitmaps embedded in the Figma file, at original resolution, plus the two gradient backgrounds.",
        "motifs": "3D brand objects for dark panels, and the three 3D product marks.",
        "backgrounds-extras": "Backgrounds and unmapped layer renders kept from the Figma file.",
        "deck": "The 45-section master pitch (47 PNGs), the 34 blank slide templates, and the brand-pitch example slides.",
        "screens": "The 10 built product screens.",
        "boards": "One PNG per Figma branding board; the completeness check.",
        "site": "Site imagery: site-assets, article headers, LinkedIn artwork sizes.",
    }

    lines = ["# RGC Assets — reference index", "",
             f"{len(entries)} files. Generated by `sync/build-asset-index.py` in the design system; regenerate after any change.", "",
             "Links: " + ("absolute, based at `" + base + "`." if base else
                          "from a URL map." if linkmap else
                          "relative paths (no host configured yet). Once the folder is hosted, re-run with `--base-url` (path-preserving hosts) or `--map` (Google Drive per-file links) to publish working URLs."), "",
             "Usage rules live in the design system: `INDEX.md`, the skill's `references/`, and the standing rules in `foundations/board-guidance.md`. Logos are placed, never redrawn; every figure in example artwork is illustrative.", ""]
    for cat in sorted(cats):
        es = cats[cat]
        lines += [f"## {cat} ({len(es)})", ""]
        if cat in BLURB: lines += [BLURB[cat], ""]
        lines += ["| File | Dimensions | Size | Link |", "|---|---|---|---|"]
        for e in es:
            name = e["path"].split("/", 1)[1] if "/" in e["path"] else e["path"]
            lines.append(f"| {name} | {e['dimensions']} | {human(e['bytes'])} | [link]({e['url']}) |")
        lines.append("")
    with open(os.path.join(root, "ASSET-INDEX.md"), "w") as f:
        f.write("\n".join(lines))
    print(f"indexed {len(entries)} files -> ASSET-INDEX.md, assets.json")

if __name__ == "__main__":
    main()
